import React, { useState, useRef, useEffect } from "react";
import { withRejectTimeout, withTimeout } from "@/domain/app/asyncUtils";
import {
  ANTI_REPEAT_BASE_RULES,
  ANTI_REPEAT_RULES,
  OOC_GUARD_RULE,
  characterHandleError,
  chatSafetyRules,
  fieldText,
  normalizeHandle,
  recentLinesBlock,
  shuffled,
  worldBridgeBlock,
} from "@/domain/app/textUtils";
import {
  canonicalDmKey,
  localRoomIdFromDmThreadKey,
  makeLocalDmRoomId,
  roomKeyFromDmThreadKey,
} from "@/domain/dm/dmKeyUtils";
import { AuthEntryScreen, AuthLoadingScreen, RecoveryScreen } from "@/features/auth/AuthScreens";
import { ConfirmScreen, DumpScreen } from "@/features/character-setup/SetupScreens";
import { DiscoverScreen } from "@/features/discover/DiscoverScreen";
import { DmListScreen } from "@/features/dm/DmListScreen";
import { HomeScreen } from "@/features/home/HomeScreen";
import { ProposalModal, RelationResultModal } from "@/features/relationships/RelationshipModals";
import { WorldChip } from "@/components/ui/WorldChip";
import { hasBackendApiConfig } from "@/api/client";
import {
  RELATION_BASE,
  LOVE_RELATIONS,
  SYMMETRIC_RELATION_BASE,
  affinityStage,
  affinityWithBase,
  attachStage,
  dirKey,
  finiteNumber,
  intimacyBoundaryRules,
  isLoveRelation,
  nameMatch,
  relationBaseFromLabel,
  relationLabelFromAffinity,
  relationStageLabel,
  symmetricRelationBaseFromLabel,
} from "@/domain/relationships/affinityUtils";
import {
  DISCOVER_POOL,
  EXAMPLES,
  MODEL_AUTO,
  MODEL_CHAT,
  MODEL_DIRECT,
  MODEL_UTIL,
  POST_MOODS,
  QUICK_FIXES,
  RENDERABLE_STEPS,
  resolveCreditReturnStep,
  TONE_PRESETS,
  type AppStep,
  hasBatchim,
  josa,
  parseRelations,
  relationMatched,
  relationTargetMatches,
  relationshipMatchRuleLine,
  selfSettingPriorityBlock,
  speechGuideLine,
  toneText,
} from "@/domain/app/aliveCore";
import { USER_PERSONA_FEATURE_ENABLED, normalizeUserPersonaSpeaker } from "@/domain/app/featureFlags";
import { hydrateFollowedCharacters } from "@/domain/discover/discoverUtils";
import { useAliveAuthActions } from "@/hooks/useAliveAuthActions";
import { useAliveAiGeneration } from "@/hooks/useAliveAiGeneration";
import { useAliveAppStatePersistence } from "@/hooks/useAliveAppStatePersistence";
import { useAliveAutosave } from "@/hooks/useAliveAutosave";
import { useAliveCharacterAnalysis } from "@/hooks/useAliveCharacterAnalysis";
import { useAliveCharacterLifecycle } from "@/hooks/useAliveCharacterLifecycle";
import { useAliveCorrections } from "@/hooks/useAliveCorrections";
import { useAliveDiscover } from "@/hooks/useAliveDiscover";
import { useAliveDiscoverActions } from "@/hooks/useAliveDiscoverActions";
import { useAliveDiscoverSync } from "@/hooks/useAliveDiscoverSync";
import { useAliveDm } from "@/hooks/useAliveDm";
import { useAliveDmGeneration } from "@/hooks/useAliveDmGeneration";
import { useAliveDmLifecycle } from "@/hooks/useAliveDmLifecycle";
import { useAliveFeed } from "@/hooks/useAliveFeed";
import { useAliveFeedGeneration } from "@/hooks/useAliveFeedGeneration";
import { useAliveFollowActions } from "@/hooks/useAliveFollowActions";
import { useAliveLocalPersistence } from "@/hooks/useAliveLocalPersistence";
import { useAliveMemory } from "@/hooks/useAliveMemory";
import { useAliveNavigation } from "@/hooks/useAliveNavigation";
import { useAlivePeerLookup } from "@/hooks/useAlivePeerLookup";
import { useAliveProfileBootstrap } from "@/hooks/useAliveProfileBootstrap";
import { useAliveRelationshipMutations } from "@/hooks/useAliveRelationshipMutations";
import { useAliveRelationships } from "@/hooks/useAliveRelationships";
import { useAliveRelationshipSync } from "@/hooks/useAliveRelationshipSync";
import { useAliveSessionBootstrap } from "@/hooks/useAliveSessionBootstrap";
import { useAliveSessionAnalysis } from "@/hooks/useAliveSessionAnalysis";
import { useAliveStructuredPersistence } from "@/hooks/useAliveStructuredPersistence";
import { useAliveSafety } from "@/hooks/useAliveSafety";
import { useCharacterAccounts } from "@/hooks/useCharacterAccounts";
import { useCharacterHandleAvailability } from "@/hooks/useCharacterHandleAvailability";

// ─────────────────────────────────────────────
//  ALIVE — 내 캐릭터가 자기 SNS를 운영한다
//  설정 입력 → 그 보이스로 피드에 글이 올라옴
//  (Claude API로 실제 생성)
// ─────────────────────────────────────────────

// 모델 선택 — 한 곳에서 관리. 실배포 시 백엔드에서 다른 제공자(Gemini Pro/Flash 등)로 교체 가능.
//  DIRECT = 사용자가 직접 치는 DM (품질 최우선, 빈도 낮음 → Sonnet / 배포 시 Pro)
//  AUTO   = 자동 생성: 자동대화·피드 글·댓글 (빈도 높아 비용 큼 → Haiku / 배포 시 Flash)
//  UTIL   = 호감도 판정·기억 추출 같은 분류/요약 (저렴한 Haiku로 충분)

export function useAliveAppController() {
  const [session, setSession] = useState(null);
  const [authMessage, setAuthMessage] = useState("");
  const [authLoading, setAuthLoading] = useState(Boolean(hasBackendApiConfig));
  const [profileLoading, setProfileLoading] = useState(Boolean(hasBackendApiConfig));
  const [profileLoadRetry, setProfileLoadRetry] = useState(0);
  const [profileName, setProfileName] = useState("");
  const [onboardingOpen, setOnboardingOpen] = useState(false);
  const [saveStatus, setSaveStatus] = useState(hasBackendApiConfig ? "로그인 대기" : "로컬 저장");
  const [characterSaveError, setCharacterSaveError] = useState("");
  const [stateReady, setStateReady] = useState(!hasBackendApiConfig);
  const [step, setStep] = useState<AppStep>("home");
  const creditReturnStepRef = useRef<AppStep>("home");
  const profileEditReturnStepRef = useRef<AppStep>("home");
  const {
    accounts,
    activeId,
    blankChar,
    char,
    deleteTarget,
    dump,
    gallery,
    handleProfileImage,
    handleUpload,
    parseError,
    parseFailed,
    parsing,
    rpLog,
    setAccounts,
    setActiveId,
    setChar,
    setDeleteTarget,
    setDump,
    setGallery,
    setParseError,
    setParseFailed,
    setParsing,
    setRpLog,
    setWaking,
    update,
    waking,
  } = useCharacterAccounts();
  const autoChatRef = useRef(false);
  const {
    activePersona,
    autoChatting,
    chatMode,
    currentWorldPref,
    defaultDmTitle,
    deletedDmKeys,
    deletePersona: deletePersonaFromDm,
    displayDmTitle,
    dm,
    dmImageDraft,
    dmInput,
    dmKey,
    dmKeyFor,
    dmPrefDraft,
    dmSending,
    dmSettingsOpen,
    dmThreadTitles,
    dmThreads,
    dmWorldDraft,
    dmWorldPrefs,
    editingDmTitle,
    handleDmImage,
    localDmKey,
    meName,
    myConversations,
    newChatMode,
    newChatSpeaker,
    ownerDmKey,
    ownerLabel,
    ownerPersona,
    ownerSpeaking,
    peer,
    pendingDm,
    personaDraft,
    personas,
    saveRenameDm,
    setAutoChatting,
    setChatMode,
    setDeletedDmKeys,
    setDmImageDraft,
    setDmInput,
    setDmPrefDraft,
    setDmSending,
    setDmSettingsOpen,
    setDmThreadTitles,
    setDmThreads,
    setDmWorldDraft,
    setDmWorldPrefs,
    setEditingDmTitle,
    setNewChatMode,
    setNewChatSpeaker,
    setOwnerPersona,
    setPeer,
    setPendingDm,
    setPersonaDraft,
    setPersonas,
    setSpeakAs,
    speakAs,
    speakerNameFor,
    startRenameDm,
  } = useAliveDm({ activeId, char });
  const isPersonaName = (name) => personas.some((persona) => persona.name === name);
  const {
    activeSharedId,
    baseFollowerCount,
    discoverQuery,
    discoverShowFollowed,
    flashShareStatus,
    followerCounts,
    followPanel,
    following,
    isFollowing,
    loadFollowerCountsFor,
    loadSharedCharacterById,
    loadSharedCharacters,
    loadSharedFollowers,
    publicFollowerCount,
    publicFollowingCount,
    publicProfile,
    recordFollowChange: recordFollowChangeFromDiscover,
    recordRelationshipFollowBack: recordRelationshipFollowBackFromDiscover,
    setActiveSharedId,
    setDiscoverQuery,
    setDiscoverShowFollowed,
    setFollowerCounts,
    setFollowPanel,
    setFollowing,
    setPublicProfile,
    setSharedCharacters,
    setSharedFocusId,
    setSharedFollowers,
    setSharedLoadState,
    setShareStatus,
    setWorldModal,
    shareCurrentCharacter: shareCurrentCharacterFromDiscover,
    sharedCharacters,
    sharedFocusId,
    sharedFollowers,
    sharedLoadState,
    shareStatus,
    shareStatusTimerRef,
    syncActiveSharedCharacter: syncActiveSharedCharacterFromDiscover,
    syncOwnFollowRows: syncOwnFollowRowsFromDiscover,
    worldModal,
  } = useAliveDiscover({
    activeId,
    char,
    profileName,
    session,
  });
  const {
    acceptTerms,
    blockedUserIds,
    blockUser,
    consentAccepted,
    consentLoaded,
    reportTarget,
    setReportTarget,
    submitReport,
    termsVersion,
  } = useAliveSafety({ session, setSaveStatus });
  const safeFollowing = following.filter((item) => !item.ownerId || !blockedUserIds.includes(item.ownerId));
  const feedFollowing = hydrateFollowedCharacters(safeFollowing, sharedCharacters);
  const {
    findPeerChar,
  } = useAlivePeerLookup({
    accounts,
    char,
    following,
    peer,
    sharedCharacters,
  });
  const {
    auto,
    canLikePost,
    commentAs,
    commentOn,
    commentText,
    autoIntervalSeconds,
    defaultCommentAs,
    deleteComment,
    deletePost,
    editingComment,
    editingPost,
    feedView,
    fixTarget,
    fixText,
    followedTimelinePosts,
    loading,
    manualPost,
    mutatePosts,
    moodOpen,
    myPosts,
    nextIn,
    openCommentBox,
    posts,
    publicPostSnapshot,
    recommendationPosts,
    recommendationUsesInterests,
    saveCommentEdit,
    savePostEdit,
    setAuto,
    setAutoInterval,
    setCommentAs,
    setCommentOn,
    setCommentText,
    setEditingComment,
    setEditingPost,
    setFeedView,
    setFixTarget,
    setFixText,
    setLoading,
    setMoodOpen,
    setPosts,
    setWriteOpen,
    setWriteText,
    sortedPosts,
    submitExternalComment,
    timeAgo,
    timelinePosts,
    isLikePending,
    toggleLike,
    visiblePosts,
    writeOpen,
    writeText,
    generateServerPost,
  } = useAliveFeed({ activeId, activeSharedId, following: feedFollowing, personas, recommendationCandidates: sharedCharacters, recommendationProfile: char, setSaveStatus, step });
  const {
    recordFollowChange,
    recordRelationshipFollowBack,
    shareCurrentCharacter,
    syncActiveSharedCharacter,
    syncOwnFollowRows,
  } = useAliveDiscoverActions({
    publicPostSnapshot,
    recordFollowChangeFromDiscover,
    recordRelationshipFollowBackFromDiscover,
    shareCurrentCharacterFromDiscover,
    syncActiveSharedCharacterFromDiscover,
    syncOwnFollowRowsFromDiscover,
  });
  const {
    addManualMemory,
    cleanMemItems,
    closeProfilePanels,
    deleteMemory,
    deleteRoomMemory,
    editMemory,
    editingMemoryId,
    loreBlockFor,
    lorePeerOptions,
    memDraftCustomPeer,
    memDraftPeer,
    memDraftText,
    memFilter,
    memSimilar,
    memTokens,
    normalizeMemoryEntry,
    renderLorePeerSelect,
    roomLoreBlockFor,
    roomMemoryEntries,
    saveMemories,
    setEditingMemoryId,
    setMemDraftCustomPeer,
    setMemDraftPeer,
    setMemDraftText,
    setMemFilter,
    setShowMemory,
    setShowMemoryAdd,
    setShowPeerMem,
    setShowRelations,
    showMemory,
    showMemoryAdd,
    showPeerMem,
    showRelations,
    toggleFollowPanel,
    toggleMemoryPanel,
    toggleRelationsPanel,
    updateLorebook,
    updateMemory,
    updateRoomMemory,
  } = useAliveMemory({
    activeId,
    activeSharedId,
    accounts,
    char,
    following,
    isPersonaName,
    loadSharedFollowers,
    myConversations,
    parseRelations,
    setAccounts,
    setChar,
    setDmWorldPrefs,
    setFollowing,
    setFollowPanel,
  });
  const {
    affOf,
    affinity,
    affinityOpen,
    canActivateSpecialRelation,
    canAutoComment,
    dmAffOf,
    followsCharacter,
    isFollowedCharacterName,
    isMyOwnChar,
    isOwnerName,
    myFollowers,
    proposal,
    relationBaseFor,
    relationFor,
    relationHintFor,
    relationResult,
    relLabelFor,
    repairRoomAffinityBase,
    roomAffOf,
    roomInitialAffinity,
    bumpRoomAffinity,
    bumpRoomMutual,
    setAffinity,
    setAffinityOpen,
    setProposal,
    setRelationResult,
    stageLabelFor,
  } = useAliveRelationships({
    accounts,
    char,
    dmWorldPrefs,
    findPeerChar,
    following,
    isPersonaName,
    parseRelations,
    relationMatched,
    relationTargetMatches,
    setDmWorldPrefs,
  });
  const {
    applyRelationshipAutoFollowsToAccounts,
    relationAutoFollowsFor,
    toggleFollow,
    verifyMutualLove,
  } = useAliveFollowActions({
    accounts,
    char,
    following,
    profileName,
    recordFollowChange,
    recordRelationshipFollowBack,
    relationBaseFor,
    relationFor,
    setAffinity,
    setFollowing,
    setPosts,
    sharedCharacters,
    syncActiveSharedCharacter,
    syncOwnFollowRows,
  });
  const proposalRef = useRef(null);
  // 진도질문 띄운 쌍 — 거절/처리 후 당분간 다시 안 물어봄 (쌍키 → true)
  const proposalCooldownRef = useRef<Record<string, boolean>>({});
  const proposingRef = useRef(false); // 진도질문 생성 중복 방지
  const dmEndRef = useRef(null);
  const loadingRef = useRef(false);
  const feedTopRef = useRef(null);
  const feedInitRef = useRef(false);
  const followBackSyncRef = useRef<Set<string>>(new Set());
  const wakingRef = useRef(false);
  const authResolvedRef = useRef(false);
  const profileLoadedRef = useRef(false);
  const profileTableBrokenRef = useRef(false);
  const saveTimerRef = useRef(null);
  const dmSendingRef = useRef(false);
  const dmRequestSeqRef = useRef(0);
  const dmKeyRef = useRef("");
  const affinityRemainderRef = useRef<Record<string, number>>({});
  const deletedDmKeysRef = useRef<Set<string>>(new Set());
  const {
    hasUsableSavedState,
    persistLocalSnapshot,
    readLocalSnapshot,
  } = useAliveLocalPersistence();
  const {
    deleteStructuredCharacterAccount,
    loadStructuredStateFallback,
    syncStructuredState,
  } = useAliveStructuredPersistence({
    deletedDmKeysRef,
    session,
    sharedCharacters,
  });
  const {
    apiContentText,
    apiErrorText,
    cleanApiFailureMessage,
    readApiContent,
    readApiJson,
  } = useAliveAiGeneration();
  const {
    advanceRelation,
    bumpAffinity,
    bumpMutual,
    deleteRelationAt,
    judgeAcceptance,
    nextRelationLabel,
    normalizeRelationLabelsForChar,
    normalizedRelationLabelFor,
    resolveProposal,
    setAffinityManual,
    setRelationLabelFor,
    setRelationToLove,
    triggerProposal,
  } = useAliveRelationshipMutations({
    accounts,
    affOf,
    affinityRemainderRef,
    char,
    findPeerChar,
    following,
    isOwnerName,
    isPersonaName,
    personas,
    proposal,
    proposalCooldownRef,
    proposingRef,
    relationBaseFor,
    relationMatched,
    relLabelFor,
    setAccounts,
    setAffinity,
    setChar,
    setFollowing,
    setProposal,
    setRelationResult,
    update,
  });
  const {
    addCorrection,
    correctionBlock,
    correctionBlockFor,
  } = useAliveCorrections({
    char,
    setAccounts,
    setChar,
  });
  const {
    judgeSession,
    processSession,
  } = useAliveSessionAnalysis({
    bumpAffinity,
    bumpRoomAffinity,
    cleanMemItems,
    isPersonaName,
    saveMemories,
  });
  const {
    addCommentFrom,
    followerPost,
    followersReactTo,
    generatePost,
    submitUserComment,
  } = useAliveFeedGeneration({
    affOf,
    bumpAffinity,
    canAutoComment,
    char,
    commentAs,
    commentText,
    findPeerChar,
    following,
    generateServerPost,
    loadingRef,
    myFollowers,
    personas,
    posts,
    relLabelFor,
    setCommentOn,
    setCommentText,
    setLoading,
    setMoodOpen,
    mutatePosts,
    setSaveStatus,
    submitExternalComment,
  });
  const {
    accountSnapshot,
    applyAppState,
    blankAppState,
    compactProfileBackup,
    exportAppState,
    profileUpsertPayload,
    resetRuntimeState,
    sanitizeSavedState,
    saveAppStateSnapshot,
  } = useAliveAppStatePersistence({
    accounts,
    activeId,
    affinity,
    blankChar,
    char,
    deletedDmKeys,
    deletedDmKeysRef,
    dmThreadTitles,
    dmThreads,
    dmWorldPrefs,
    feedInitRef,
    following,
    gallery,
    onboardingOpen,
    ownerPersona,
    persistLocalSnapshot,
    personas,
    posts,
    profileName,
    profileTableBrokenRef,
    session,
    syncStructuredState,
    setAccounts,
    setActiveId,
    setActiveSharedId,
    setAffinity,
    setChar,
    setCommentOn,
    setCommentText,
    setDeletedDmKeys,
    setDiscoverQuery,
    setDmInput,
    setDmThreads,
    setDmThreadTitles,
    setDmWorldPrefs,
    setEditingDmTitle,
    setFollowerCounts,
    setFollowing,
    setGallery,
    setNewChatMode,
    setOwnerPersona,
    setPeer,
    setPersonas,
    setPosts,
    setProfileName,
    setSaveStatus,
    setSharedFocusId,
    setShareStatus,
    setStep,
  });

  const {
    clearLocalAuthStorage,
    completeOnboarding,
    deleteAccount,
    readableAuthError,
    recoverAuthScreen,
    signInWithProvider,
    signInWithToss,
    signOut,
  } = useAliveAuthActions({
    profileName,
    profileTableBrokenRef,
    resetRuntimeState,
    session,
    setAuthLoading,
    setAuthMessage,
    setOnboardingOpen,
    setProfileLoading,
    setProfileName,
    setSaveStatus,
    setSession,
    setStateReady,
    setStep,
  });
  useAliveAutosave({
    accounts,
    activeId,
    affinity,
    char,
    deletedDmKeys,
    discoverQuery,
    dmThreadTitles,
    dmThreads,
    dmWorldPrefs,
    exportAppState,
    following,
    gallery,
    onboardingOpen,
    ownerPersona,
    personas,
    persistLocalSnapshot,
    profileLoadedRef,
    profileName,
    profileTableBrokenRef,
    profileUpsertPayload,
    saveTimerRef,
    session,
    setSaveStatus,
    stateReady,
    syncStructuredState,
  });

  const canUseApp = !hasBackendApiConfig || (session && stateReady && consentLoaded && consentAccepted);
  const authBusy = hasBackendApiConfig && (authLoading || profileLoading || (session && (!stateReady || !consentLoaded)));
  const appScreenVisible = canUseApp && (
    ["home", "credits", "dump", "confirm", "feed", "discover", "dmlist"].includes(step)
    || (step === "dm" && peer)
  );
  const needsSafetyConsent = Boolean(hasBackendApiConfig && session && consentLoaded && !consentAccepted);
  const hasMainScreen = authBusy || needsSafetyConsent || (hasBackendApiConfig && !authLoading && !session) || appScreenVisible;
  const showRecoveryScreen = !hasMainScreen;
  const openCredits = (): void => {
    if (step !== "credits") creditReturnStepRef.current = step;
    setStep("credits");
  };
  const closeCredits = (): void => {
    setStep(resolveCreditReturnStep(creditReturnStepRef.current, Boolean(activeId)));
  };
  const {
    navApplyingRef,
    navInitRef,
    navKey,
    navLastKeyRef,
    navStateForHistory,
    navUrlForState,
  } = useAliveNavigation({
    activeId,
    canUseApp,
    dmSettingsOpen,
    dmWorldDraft,
    followPanel,
    newChatMode,
    pendingDm,
    publicProfile,
    setDmSettingsOpen,
    setDmWorldDraft,
    setFollowPanel,
    setNewChatMode,
    setPendingDm,
    setPublicProfile,
    setStep,
    step,
  });
  useAliveSessionBootstrap({
    applyAppState,
    authBusy,
    authResolvedRef,
    clearLocalAuthStorage,
    profileLoadedRef,
    readLocalSnapshot,
    readableAuthError,
    resetRuntimeState,
    setAuthLoading,
    setAuthMessage,
    setProfileLoading,
    setSaveStatus,
    setSession,
    setStateReady,
  });
  useAliveProfileBootstrap({
    applyAppState,
    blankAppState,
    hasUsableSavedState,
    loadStructuredStateFallback,
    profileLoadedRef,
    profileLoadRetry,
    profileTableBrokenRef,
    readLocalSnapshot,
    session,
    setAuthMessage,
    setOnboardingOpen,
    setProfileLoading,
    setProfileName,
    setSaveStatus,
    setStateReady,
  });

  useEffect(() => {
    if (!canUseApp) return;
    const needsActiveCharacter = ["feed", "discover", "dmlist", "dm"].includes(step);
    if (!RENDERABLE_STEPS.has(step) || (step === "dm" && !peer) || (needsActiveCharacter && !activeId)) {
      setPeer(null);
      setStep("home");
    }
  }, [canUseApp, step, activeId, peer]); // eslint-disable-line
  useAliveDiscoverSync({
    activeId,
    activeSharedId,
    canUseApp,
    char,
    following,
    followBackSyncRef,
    loadFollowerCountsFor,
    loadSharedCharacterById,
    loadSharedCharacters,
    recordRelationshipFollowBack,
    session,
    setActiveSharedId,
    setDiscoverQuery,
    setPublicProfile,
    setSharedFocusId,
    setStep,
    step,
    verifyMutualLove,
  });
  useAliveRelationshipSync({
    accounts,
    activeId,
    affinity,
    applyRelationshipAutoFollowsToAccounts,
    canUseApp,
    char,
    following,
    normalizeRelationLabelsForChar,
    relationAutoFollowsFor,
    setAccounts,
    setChar,
    setFollowing,
    stateReady,
    syncActiveSharedCharacter,
    syncOwnFollowRows,
  });

  const {
    chooseDmWorldMode,
    deleteDmThread,
    enterDm,
    finishDmChatKind,
    finishDmWorldSetup,
    openDmSettings,
    requestDmEntry,
    resetAffinityForDmThread,
    saveDmSettings,
    setDmThread,
  } = useAliveDmLifecycle({
    accounts,
    activePersona,
    affinityRemainderRef,
    char,
    currentWorldPref,
    deletedDmKeys,
    deletedDmKeysRef,
    dmKey,
    dmKeyFor,
    dmKeyRef,
    dmPrefDraft,
    dmRequestSeqRef,
    dmSending,
    dmSendingRef,
    dmThreads,
    dmThreadTitles,
    dmWorldDraft,
    dmWorldPrefs,
    exportAppState,
    findPeerChar,
    following,
    isOwnerName,
    isPersonaName,
    localDmKey,
    ownerLabel,
    peer,
    pendingDm,
    persistLocalSnapshot,
    proposalCooldownRef,
    relationHintFor,
    relationMatched,
    relLabelFor,
    repairRoomAffinityBase,
    roomInitialAffinity,
    saveAppStateSnapshot,
    session,
    setAffinity,
    setDeletedDmKeys,
    setDmPrefDraft,
    setDmSending,
    setDmSettingsOpen,
    setDmThreads,
    setDmThreadTitles,
    setDmWorldDraft,
    setDmWorldPrefs,
    setNewChatMode,
    setPeer,
    setPendingDm,
    setRelationLabelFor,
    setSpeakAs,
    setStep,
    speakAs,
    speakerNameFor,
    syncStructuredState,
    step,
  });
  const {
    genLine,
    sendDM,
    startAutoChat,
    stopAutoChat,
  } = useAliveDmGeneration({
    activePersona,
    affOf,
    autoChatRef,
    bumpAffinity,
    bumpMutual,
    bumpRoomAffinity,
    bumpRoomMutual,
    char,
    chatMode,
    cleanApiFailureMessage,
    correctionBlockFor,
    currentWorldPref,
    dm,
    dmAffOf,
    dmImageDraft,
    dmInput,
    dmKey,
    dmKeyRef,
    dmRequestSeqRef,
    dmSendingRef,
    findPeerChar,
    gallery,
    loreBlockFor,
    meName,
    ownerLabel,
    ownerPersona,
    peer,
    processSession,
    proposalRef,
    proposingRef,
    relationHintFor,
    relationMatched,
    roomAffOf,
    roomLoreBlockFor,
    setAutoChatting,
    setDmImageDraft,
    setDmInput,
    setDmSending,
    setDmThread,
    setSaveStatus,
    speakAs,
  });
  const {
    parseDump,
  } = useAliveCharacterAnalysis({
    cleanApiFailureMessage,
    dump,
    rpLog,
    setChar,
    setLoading,
    setParseError,
    setParseFailed,
    setParsing,
    setStep,
  });

  const handleAvailability = useCharacterHandleAvailability(char.handle, activeId);
  const handleError = characterHandleError(char.handle);
  const confirmReady = Boolean(char.name.trim() && char.persona.trim() && !handleError && handleAvailability.state !== "taken");
  useEffect(() => setCharacterSaveError(""), [char.handle]);

  const {
    confirmDeleteCharacter,
    editAccount,
    goHome,
    saveCharacterEdits,
    startNewCharacter,
    switchAccount,
    syncActive,
    wakeCharacter,
  } = useAliveCharacterLifecycle({
    accountSnapshot,
    accounts,
    activeId,
    applyRelationshipAutoFollowsToAccounts,
    blankChar,
    char,
    deleteStructuredCharacterAccount,
    deleteTarget,
    dmThreads,
    dmWorldPrefs,
    exportAppState,
    feedInitRef,
    following,
    gallery,
    persistLocalSnapshot,
    posts,
    relationAutoFollowsFor,
    saveAppStateSnapshot,
    setAccounts,
    setActiveId,
    setChar,
    setCharacterSaveError,
    setDeleteTarget,
    setDmThreads,
    setDmWorldPrefs,
    setDump,
    setFollowing,
    setGallery,
    setParseError,
    setParseFailed,
    setPeer,
    setPosts,
    setRpLog,
    setSaveStatus,
    setStep,
    setWaking,
    syncActiveSharedCharacter,
    syncOwnFollowRows,
    wakingRef,
  });

  function editAccountFromHome(id: string): void {
    profileEditReturnStepRef.current = "home";
    editAccount(id);
  }

  function editActiveProfile(): void {
    if (!activeId) return;
    profileEditReturnStepRef.current = "feed";
    editAccount(activeId);
  }

  function exitProfileEdit(): void {
    setStep(profileEditReturnStepRef.current);
  }

  function clearActiveProfileImage(kind: "avatar" | "header"): void {
    const field = kind === "avatar" ? "avatarImg" : "headerImg";
    update(field, "");
    if (!activeId) return;
    setAccounts((items) => items.map((account) => account.id === activeId ? { ...account, char: { ...account.char, [field]: "" } } : account));
  }

  function deletePersona(id) {
    deletePersonaFromDm(id, commentAs, setCommentAs);
  }

  // ───────── 호감도 ─────────
  const PROPOSAL_THRESHOLD = 60;
  const OWNER = "나";
  // DM 새 메시지 시 맨 아래로
  useEffect(() => {
    if (step === "dm" && dmEndRef.current) {
      dmEndRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [dm, step]);

  // 방 바뀌면 오너 끼어들기만 해제 (페르소나/캐릭터 선택은 보존 — 목록에서 복원되므로)
  useEffect(() => { setSpeakAs((s) => s === "owner" ? "char" : s); }, [peer && peer.name, peer && peer.asOwner]);
  useEffect(() => {
    if (USER_PERSONA_FEATURE_ENABLED) return;
    setCommentAs((value) => normalizeUserPersonaSpeaker(value));
    setSpeakAs((value) => normalizeUserPersonaSpeaker(value));
    setNewChatSpeaker((value) => normalizeUserPersonaSpeaker(value));
    setNewChatMode((value) => value === "persona" ? null : value);
    setPersonaDraft(null);
  }, []);
  // 진도질문 모달 상태를 ref에 미러 (자동대화 루프에서 최신값 참조)
  useEffect(() => { proposalRef.current = proposal; }, [proposal]);

  const appViewCtx = {
    acceptTerms,
    accounts,
    accountSnapshot,
    activeId,
    activePersona,
    activeSharedId,
    addCommentFrom,
    addCorrection,
    addManualMemory,
    advanceRelation,
    affinity,
    affinityOpen,
    affinityRemainderRef,
    affinityStage,
    affinityWithBase,
    affOf,
    ANTI_REPEAT_BASE_RULES,
    ANTI_REPEAT_RULES,
    apiContentText,
    apiErrorText,
    applyAppState,
    applyRelationshipAutoFollowsToAccounts,
    appScreenVisible,
    attachStage,
    authBusy,
    AuthEntryScreen,
    authLoading,
    AuthLoadingScreen,
    authMessage,
    authResolvedRef,
    auto,
    autoIntervalSeconds,
    canLikePost,
    autoChatRef,
    autoChatting,
    baseFollowerCount,
    blockedUserIds,
    blankAppState,
    blankChar,
    bumpAffinity,
    bumpMutual,
    bumpRoomAffinity,
    bumpRoomMutual,
    blockUser,
    canActivateSpecialRelation,
    canAutoComment,
    canonicalDmKey,
    canUseApp,
    char,
    characterSaveError,
    clearActiveProfileImage,
    chatMode,
    chatSafetyRules,
    chooseDmWorldMode,
    cleanApiFailureMessage,
    cleanMemItems,
    clearLocalAuthStorage,
    closeProfilePanels,
    closeCredits,
    commentAs,
    commentOn,
    commentText,
    compactProfileBackup,
    completeOnboarding,
    consentAccepted,
    consentLoaded,
    confirmDeleteCharacter,
    confirmReady,
    ConfirmScreen,
    correctionBlock,
    correctionBlockFor,
    currentWorldPref,
    defaultCommentAs,
    defaultDmTitle,
    deleteComment,
    deleteAccount,
    deletedDmKeys,
    deletedDmKeysRef,
    deleteDmThread,
    deleteMemory,
    deletePersona,
    deletePost,
    deleteRelationAt,
    deleteRoomMemory,
    deleteStructuredCharacterAccount,
    deleteTarget,
    dirKey,
    DISCOVER_POOL,
    discoverQuery,
    DiscoverScreen,
    discoverShowFollowed,
    displayDmTitle,
    dm,
    dmAffOf,
    dmEndRef,
    dmImageDraft,
    dmInput,
    dmKey,
    dmKeyFor,
    dmKeyRef,
    DmListScreen,
    dmPrefDraft,
    dmRequestSeqRef,
    dmSending,
    dmSendingRef,
    dmSettingsOpen,
    dmThreads,
    dmThreadTitles,
    dmWorldDraft,
    dmWorldPrefs,
    dump,
    DumpScreen,
    editAccount: editAccountFromHome,
    editActiveProfile,
    editingComment,
    editingDmTitle,
    editingMemoryId,
    editingPost,
    editMemory,
    enterDm,
    EXAMPLES,
    exitProfileEdit,
    exportAppState,
    feedInitRef,
    feedTopRef,
    feedView,
    fieldText,
    findPeerChar,
    finishDmChatKind,
    finishDmWorldSetup,
    finiteNumber,
    fixTarget,
    fixText,
    flashShareStatus,
    followBackSyncRef,
    followedTimelinePosts,
    followerCounts,
    followerPost,
    followersReactTo,
    following,
    followPanel,
    followsCharacter,
    gallery,
    generatePost,
    genLine,
    goHome,
    handleDmImage,
    handleProfileImage,
    handleAvailability,
    handleError,
    hasBackendApiConfig,
    handleUpload,
    hasMainScreen,
    hasUsableSavedState,
    HomeScreen,
    intimacyBoundaryRules,
    isFollowing,
    isFollowedCharacterName,
    isLoveRelation,
    isMyOwnChar,
    isOwnerName,
    isPersonaName,
    josa,
    judgeAcceptance,
    judgeSession,
    loadFollowerCountsFor,
    loading,
    loadingRef,
    loadSharedCharacterById,
    loadSharedCharacters,
    loadSharedFollowers,
    loadStructuredStateFallback,
    localDmKey,
    localRoomIdFromDmThreadKey,
    loreBlockFor,
    lorePeerOptions,
    LOVE_RELATIONS,
    makeLocalDmRoomId,
    manualPost,
    memDraftCustomPeer,
    memDraftPeer,
    memDraftText,
    memFilter,
    memSimilar,
    memTokens,
    meName,
    moodOpen,
    myConversations,
    myFollowers,
    myPosts,
    nameMatch,
    navApplyingRef,
    navInitRef,
    navKey,
    navLastKeyRef,
    navStateForHistory,
    navUrlForState,
    newChatMode,
    newChatSpeaker,
    nextIn,
    nextRelationLabel,
    normalizedRelationLabelFor,
    normalizeHandle,
    normalizeMemoryEntry,
    normalizeRelationLabelsForChar,
    onboardingOpen,
    openCredits,
    OOC_GUARD_RULE,
    openCommentBox,
    openDmSettings,
    OWNER,
    ownerDmKey,
    ownerLabel,
    ownerPersona,
    ownerSpeaking,
    parseDump,
    parseError,
    parseFailed,
    parseRelations,
    parsing,
    peer,
    pendingDm,
    persistLocalSnapshot,
    personaDraft,
    personas,
    posts,
    processSession,
    profileLoadedRef,
    profileLoading,
    profileLoadRetry,
    profileEditBackLabel: profileEditReturnStepRef.current === "feed" ? "피드로" : "목록으로",
    profileName,
    profileTableBrokenRef,
    profileUpsertPayload,
    proposal,
    PROPOSAL_THRESHOLD,
    proposalCooldownRef,
    ProposalModal,
    proposalRef,
    proposingRef,
    publicFollowerCount,
    publicFollowingCount,
    publicPostSnapshot,
    recommendationPosts,
    recommendationUsesInterests,
    publicProfile,
    reportTarget,
    POST_MOODS,
    QUICK_FIXES,
    readableAuthError,
    readApiContent,
    readApiJson,
    readLocalSnapshot,
    recentLinesBlock,
    recordFollowChange,
    recordRelationshipFollowBack,
    recoverAuthScreen,
    RecoveryScreen,
    RELATION_BASE,
    relationAutoFollowsFor,
    relationBaseFor,
    relationBaseFromLabel,
    relationMatched,
    relationFor,
    relationHintFor,
    relationLabelFromAffinity,
    relationResult,
    RelationResultModal,
    relationStageLabel,
    relLabelFor,
    renderLorePeerSelect,
    repairRoomAffinityBase,
    requestDmEntry,
    resetAffinityForDmThread,
    resetRuntimeState,
    resolveProposal,
    roomAffOf,
    roomInitialAffinity,
    roomKeyFromDmThreadKey,
    roomLoreBlockFor,
    roomMemoryEntries,
    rpLog,
    sanitizeSavedState,
    saveAppStateSnapshot,
    saveCharacterEdits,
    saveCommentEdit,
    saveDmSettings,
    saveMemories,
    savePostEdit,
    saveRenameDm,
    saveStatus,
    saveTimerRef,
    sendDM,
    session,
    setAccounts,
    setActiveId,
    setActiveSharedId,
    setAffinity,
    setAffinityManual,
    setAffinityOpen,
    setAuthLoading,
    setAuthMessage,
    setAuto,
    setAutoInterval,
    setAutoChatting,
    setChar,
    setChatMode,
    setCommentAs,
    setCommentOn,
    setCommentText,
    setDeletedDmKeys,
    setDeleteTarget,
    setDiscoverQuery,
    setDiscoverShowFollowed,
    setDmImageDraft,
    setDmInput,
    setDmPrefDraft,
    setDmSending,
    setDmSettingsOpen,
    setDmThread,
    setDmThreads,
    setDmThreadTitles,
    setDmWorldDraft,
    setDmWorldPrefs,
    setDump,
    setEditingComment,
    setEditingDmTitle,
    setEditingMemoryId,
    setEditingPost,
    setFeedView,
    setFixTarget,
    setFixText,
    setFollowerCounts,
    setFollowing,
    setFollowPanel,
    setGallery,
    setLoading,
    setMemDraftCustomPeer,
    setMemDraftPeer,
    setMemDraftText,
    setMemFilter,
    setMoodOpen,
    setNewChatMode,
    setNewChatSpeaker,
    setOnboardingOpen,
    setOwnerPersona,
    setParseError,
    setParseFailed,
    setParsing,
    setPeer,
    setPendingDm,
    setPersonaDraft,
    setPersonas,
    setPosts,
    setProfileLoading,
    setProfileLoadRetry,
    setProfileName,
    setProposal,
    setPublicProfile,
    setReportTarget,
    setRelationLabelFor,
    setRelationResult,
    setRelationToLove,
    setRpLog,
    setSaveStatus,
    setSession,
    setSharedCharacters,
    setSharedFocusId,
    setSharedFollowers,
    setSharedLoadState,
    setShareStatus,
    setShowMemory,
    setShowMemoryAdd,
    setShowPeerMem,
    setShowRelations,
    setSpeakAs,
    setStateReady,
    setStep,
    setWaking,
    setWorldModal,
    setWriteOpen,
    setWriteText,
    shareCurrentCharacter,
    sharedCharacters,
    sharedFocusId,
    sharedFollowers,
    sharedLoadState,
    shareStatus,
    shareStatusTimerRef,
    showMemory,
    showMemoryAdd,
    showPeerMem,
    showRecoveryScreen,
    showRelations,
    shuffled,
    signInWithProvider,
    signInWithToss,
    signOut,
    sortedPosts,
    submitExternalComment,
    speakAs,
    speakerNameFor,
    stageLabelFor,
    startAutoChat,
    startNewCharacter,
    startRenameDm,
    stateReady,
    step,
    stopAutoChat,
    submitUserComment,
    submitReport,
    switchAccount,
    SYMMETRIC_RELATION_BASE,
    symmetricRelationBaseFromLabel,
    syncActive,
    syncActiveSharedCharacter,
    syncOwnFollowRows,
    syncStructuredState,
    timeAgo,
    termsVersion,
    timelinePosts,
    isLikePending,
    toggleFollow,
    toggleFollowPanel,
    toggleLike,
    toggleMemoryPanel,
    toggleRelationsPanel,
    toneText,
    triggerProposal,
    update,
    updateLorebook,
    updateMemory,
    updateRoomMemory,
    verifyMutualLove,
    visiblePosts,
    wakeCharacter,
    waking,
    wakingRef,
    withRejectTimeout,
    withTimeout,
    worldBridgeBlock,
    WorldChip,
    worldModal,
    writeOpen,
    writeText,
  };

  return appViewCtx;
}
